### PR TITLE
Implement feature request: Annotation in the manifest can be used to specify optional

### PR DESCRIPTION
**Pull request by ryo-yamaoka**
Fixes: #476

## Behavior

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: optional-test-manifest-deployment
  labels:
    app: optional-test-manifest
  annotations:
    kube-score/ignore: pod-networkpolicy,container-resources,container-image-pull-policy,container-security-context-privileged,container-security-context-user-group-id,container-security-context-readonlyrootfilesystem,container-ephemeral-storage-request-and-limit
    kube-score/optional: container-seccomp-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: optional-test-manifest
  template:
    metadata:
      labels:
        app: optional-test-manifest
    spec:
      containers:
      - name: optional-test-manifest
        image: busybox:1.34
        command:
        - /bin/sh
        - -c
        - date; env; tail -f /dev/null
```

```
$ kube-score score manifest.yaml
apps/v1/Deployment optional-test-manifest-deployment                          🤔
    [WARNING] Container Seccomp Profile
        · The pod has not configured Seccomp for its containers
            Running containers with Seccomp is recommended to reduce the kernel attack surface
```

### Annotations ignore

```
$ kube-score score manifest.yaml --disable-optional-checks-annotations
apps/v1/Deployment optional-test-manifest-deployment                          ✅
```

### (FYI) Both defined

It will be marked to `ignored`

```yaml
  annotations:
    kube-score/ignore: container-seccomp-profile
    kube-score/optional: container-seccomp-profile
```

```
$ kube-score score manifest.yaml --output-format ci | grep seccomp
[SKIPPED] optional-test-manifest-deployment apps/v1/Deployment: Skipped because container-seccomp-profile is ignored
```

### CODE REVIEW

**Review by zegl — APPROVED** [review]
Looks great! Good idea, and thanks for implementing it!

Just a quick thing, what do you think about renaming the annotation to `kube-score/enable`?

I think that that way it's more clear that this annotation enables additional checks, to avoid confusion with maybe marking a check as optional to pass. If that makes sense.

**Comment by ryo-yamaoka** [comment]
Thanks for review and suggest!
I think it is a good.
But sorry, I'm going camping now, so the fix will have to wait until Sunday.

**Comment by ryo-yamaoka** [comment]
Oops test timed-out...?
It succeeds in my local env. Can you rerun CircleCI workflow?
https://app.circleci.com/pipelines/github/zegl/kube-score/1555/workflows/616a8b9c-0287-49ea-887b-70796e4e9b00/jobs/1814/parallel-runs/0/steps/0-104

**Comment by zegl** [comment]
I was thinking to only rename the new annotation that you've added. Renaming the `--enable-optional-test` flag is a breaking change, and while it would be nice to rename that flag as well. We need to do it in a way that doesn't break backwards compatibility.

The rest looks great tough!

**Comment by zegl** [comment]
I've restarted the CircleCI job

**Comment by ryo-yamaoka** [comment]
Sorry, breaking change was certainly out of the question.
Also, I think removing the Optional halfway through in the code was not a good idea.

I reverted that and fix to only annotation renamed.
https://github.com/zegl/kube-score/pull/477/commits/fc50291e9ab76c7dbf7e1f73ba9ff20835724121

**Review by zegl — APPROVED** [review]
LGTM! Nice stuff! 👍

**Pull request merged**
