### PR TITLE
render/junit: add new output

### LINKED ISSUE #459: Feature request: Support JUnit XML output format
I've experimented a bit with this tool on some YAML files at work. The output format is currently limited to `human` (which is neat for just finding and fixing potential issues) and `ci` (just one line per test). It'd be nice to support also [junit](https://llg.cubic.org/docs/junit/). This format allows to see the results more clearly for each of the tests. JUnit is supported also by GitLab, and on other platforms (GitHub), and despite the misleading name, it appears to be a more universal format.

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=trx%2Cyaml
https://docs.gitlab.com/ee/ci/unit_test_reports.html
https://support.atlassian.com/bitbucket-cloud/docs/test-reporting-in-pipelines/

### PR DESCRIPTION
**Pull request by sebhoss**
This produces JUnit XML compatible output when the 'junit' output format is specified.

Fixes #459

```
RELNOTE: Add JUnit output format option
```

### CODE REVIEW

**Comment by zegl** [comment]
Thanks for the PR! I'll take a look at it over the weekend.

**Comment by sebhoss** [comment]
thanks a lot! I wasn't really sure about the data structures used by kube-scoren, so I'm happy to change all code in this PR to whatever works best for you 👍

**Comment by gruzchik** [comment]
Hey guys! @zegl , @sebhoss  could you please let us know when you merge and update this feature. We are using Gitlab and I have proposed to use kube-score for validation, it would be nice to be able to use JUnit to implement kube-score

**Comment by zegl** [comment]
I found that the output format was not added to main.go (and was not considered a valid option), other than that, looks good!

**Comment by sebhoss** [comment]
This is really cool - thanks a lot @zegl!

**Comment by gruzchik** [comment]
@sebhoss , @zegl  very appreciated for your work!  I'm looking forward to adding this update to the release, it would be nice to have opportunity to use this as an official stable version

**Comment by salzig** [comment]
Ah, nice to know. Thanks!

Sadly it's not mentioned in the usage.

**Comment by gruzchik** [comment]
> Ah, nice to know. Thanks!
> 
> Sadly it's not mentioned in the usage.

Hi @salzig , As I see this update was already  included to the latest release Oct 1 2024, you can use it with the latest version https://github.com/zegl/kube-score/releases/tag/v1.19.0

**Pull request merged**
