### PR TITLE
Introduce golangci-lint

### PR DESCRIPTION
**Pull request by atombrella**
There are some commented out linters that create a fair share of warnings, e.g., `govet`. Don't know how you feel about fixing the warnings from them, before merging.

### CODE REVIEW

**Comment by zegl** [comment]
This is really nice! I'll merge this and we can work to enable more linters over time. 👍

**Review by zegl — APPROVED** [review]
bors merge

**Comment by atombrella** [comment]
> This is really nice! I'll merge this and we can work to enable more linters over time. +1

:tada: You can consider creating an issue with the label good first issue to enable the remaining linters, and possibly also adding the label `hacktoberfest` to the repository. The cyclomatic complexity setting of 35 seems like a hack.

**Comment by zegl** [comment]
Smart, let's do it. :-)

**Pull request merged**
